### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by pbrisbin** [MikaelCluseau/http2kafka#1]
I'm trying to add support for keyed messages (adding a `Key` header). But I'm unable to build the project:

```
[ERROR] Failed to execute goal on project http2kafka: Could not resolve dependencies for project nc.isi:http2kafka:jar:0.0.1-SNAPSHOT: Could not find artifact org.simpleframework:simpleweb:jar:5.1.6 in central (http://repo.maven.apache.org/maven2) -> [Help 1]
```

I'm having trouble finding information on this `simpleweb` artifact. Can you help?

**Comment by pbrisbin** [comment]
Sorry, I just found the section in the README. That gets me further:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.825s
[INFO] Finished at: Wed Jul 08 16:42:28 UTC 2015
[INFO] Final Memory: 7M/114M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project http2kafka: Compilation failure
[ERROR] Unable to locate the Javac Compiler in:
[ERROR] /usr/lib/jvm/java-7-openjdk-amd64/jre/../lib/tools.jar
[ERROR] Please ensure you are using JDK 1.4 or above and
[ERROR] not a JRE (the com.sun.tools.javac.Main class is required).
[ERROR] In most cases you can change the location of your Java
[ERROR] installation by setting the JAVA_HOME environment variable.
```

**Comment by pbrisbin** [comment]
I was able to get it all building by changing the `FROM` to `java:openjdk-7-jdk`

Note: I'm using an overall `Dockerfile` that does the `maven` stuff during `docker build` rather than requiring a local Java setup and just copying in a pre-built jar file.

**Comment by mcluseau** [comment]
Hi, thank you for you interest :-)

I just copy the pre-built jar-ifle because I try to have the smallest possible docker image at the end of the process. The idea is to be as close as possible to a statically linked binary added in a docker this way:

```
from scratch
add my-binary /
entrypoint /my-binary
```

For sure, there is a way to do a "build docker", I just didn't had the time to do that (and that's definitely something I want from an CI/CD point of view).

**Comment by pbrisbin** [comment]
Cool, I basically did it because I didn't have a proper local java set up (and didn't really want one). You can see my work here: https://github.com/codeclimate/http2kafka if any of it looks worth upstreaming, let me know and I can make a proper PR.

**Comment by mcluseau** [comment]
A new feature is certainly worth upstreaming, optimizing the resulting docker can be made later. We may also think about a "Partition" header.
